### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by khang152xx** [BreakingTV/LoRPresence#1]
I don't know anything about coding or anything like that, including how to use Node.js. Can you provide more specific guidance?

**Comment by BreakingTV** [comment]
oh, forgot to mention, use: node app.js in the same folder

**Comment by khang152xx** [comment]
![Untitled](https://github.com/BreakingTV/LoRPresence/assets/146123413/a73532ce-79f6-4b91-b580-d6a101d73236)
LOL, If it's showing 'MODULE_NOT_FOUND,' what should I do?

**Comment by BreakingTV** [comment]
you need to: cd src/
and then again write node app.js

**Comment by khang152xx** [comment]
Thank you, it's working fine now. However, the RPC isn't displaying any images, but anyway, I appreciate your help. I'll wait for this project to be completed.

**Comment by khang152xx** [comment]
I hope this project will support Vietnamese langue as well.

**Comment by BreakingTV** [comment]
I don't know why it doesn't show images... never really worked with discord RPC will look into that, thank you anyway
Maybe I will add Language files, so other people can add their language... because I can't t Vietnamese...
Anyway, thanks!
